title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend El-Manihawy</p> <p style="font-size:20px;font-style:italic;">Data Analyst </p>
show_downloads: true
theme: jekyll-theme-cayman
